### ISSUE TITLE
Performance issue with `fuchsify` and `git_410.mtx`

### ISSUE THREAD

**Issue by gituliar** [gituliar/delirium#2]
It takes too long to reduce `test/data/git_410.mtx` matrix with `fuchsify` function. I tried to examine what is the reason and whether it is possible to improve the performance; for that purpose I added a "--profile" option to "delirium". It looks like the code spends too much time in Sage's `is_zero` method, but I did not figure out how to improve that behaviour. @magv can you take a look at this issue?

BTW, when reducing the same matrix with Maple's `super_reduce` the performance depends on the order of points you reduce at, e.g. {x+1, x, x-1} or {x, x-1, x+1}. Is `fuchsify` sensitive to such ordering?

**Comment by magv** [comment]
> It takes too long to reduce `test/data/git_410.mtx` matrix with `fuchsify` function.

Too long? So it does actually finish at some point? Those are good news then, I thought it hung completely... I haven't had the time to investigate this problem yet, but I'll look into it.

> BTW, when reducing the same matrix with Maple's super_reduce the performance depends on the order of points you reduce at, e.g. {x+1, x, x-1} or {x, x-1, x+1}.

Does it vary significantly? If super_reduce does simple stepwise Moser reduction, then I wouldn't expect more that, say, 50% variation.

> Is `fuchsify` sensitive to such ordering?

Yes. Performance depends both the order of points you reduce at, and the order of points you try to reduce to (the last part is specific to Lee's algorithm). The difference can be fairly significant, especially if multiple extra singularities are introduced.

You can try running `fuchsify` with different `seed` values to see some of the variation (there's a part of `fuchsify` that doesn't yet respect this seed though).

**Comment by gituliar** [comment]
> > It takes too long to reduce `test/data/git_410.mtx` matrix with `fuchsify` function.
> 
> Too long? So it does actually finish at some point? Those are good news then, I thought it hung completely... I haven't had the time to investigate this problem yet, but I'll look into it.

No good news, it does not finish.

> > BTW, when reducing the same matrix with Maple's super_reduce the performance depends on the order of points you reduce at, e.g. {x+1, x, x-1} or {x, x-1, x+1}.
> 
> Does it vary significantly? If super_reduce does simple stepwise Moser reduction, then I wouldn't expect more that, say, 50% variation.

All combinations take about the same time to finish, but one: x, x-1, x+1; here is what I got:

```
$ time delirium reduce --maple -o git_410_x_x-1_x+1.mtx -p x+1 git_410_x_x-1.mtx
Delirium v16.02.02
Authors:
    Oleksandr Gituliar, The PAS Institute of Nuclear Physics, Krakow (Poland)
    Vitaly Magerya

ECL says: THROW: The catch MACSYMA-QUIT is undefined.

real    3m42.080s
user    2m46.470s
sys     0m0.717s
```

Also note that `git_410_x_x+1_x-1.mtx` and `git_410_x_x-1.mtx` are ~8 times bigger than corresponding matrices reduced in different secuences.

**Comment by magv** [comment]
As of commit 3f55e4888b4e342331a16d3d66b97334a3483f1c `fuchsify` should be able to reduce `git_410.mtx` in about a minute.

**Comment by gituliar** [comment]
As of commit febf92fd187d9fc90668e86bce3e3eaf4dfa8448 the problem remains; though, when I take eps=0 limit the result comes smoothly in a few seconds. I use 'SageMath Version 7.0, Release Date: 2016-01-19', maybe that is a problem since the release is quite fresh. Any ideas?

**Comment by magv** [comment]
I don't know what to tell you. I'm seeing 54s of runtime with the default seed, and 11s with `seed=1`. This is with Sage 6.10 of course, but I wouldn't expect there to be a difference unless they changed the way their linear equation solver works.

**Comment by gituliar** [comment]
With `seed=1` it takes 42s for me, at least it does not hang. I close this issue since it looks like playing with the seed soves the problem.

PS. _It looks like we need more control on what is going on._ So far we have to apply `simplify_rational` in "hot" places, tune seed, and all these higher-order `eps`-polynoms in the final result; that does not look good. Today I also discovered a bug in Sage: `matrix(SR, [[1,0,0],[0,0,0],[0,0,0]]).eigenvectors_right()` does not return 1 and its eigenvector. Looks like Sage is not stable enough for this project.

**Comment by magv** [comment]
> Today I also discovered a bug in Sage: `matrix(SR, [[1,0,0],[0,0,0],[0,0,0]]).eigenvectors_right()` does not return 1 and its eigenvector.

Really? Do our unit tests even pass if this is the case?
